version: "3.8"
services:

    db:
        image: mysql
        container_name: db_docker_toukan
        volumes:
            - toukan-db-data:/var/lib/mysql
        environment:
            MYSQL_USER: 'toukan'
            MYSQL_PASSWORD: 'toukan'
            MYSQL_DATABASE: 'toukan'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_toukan
        depends_on:
            - db
        ports:
            - "8082:80"
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_docker_toukan
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        networks:
            - dev

    www:
        build: docker/php
        container_name: www_docker_toukan
        ports:
            - "8080:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./app:/var/www
        networks:
            - dev

networks:
    dev:

volumes:
    toukan-db-data:
